import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import Header from "../components/Header";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>CelloTree</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="grid grid-cols-sidbar min-h-screen text-white  bg-primary ">
      {/* <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          <Link href="/protected" className="text-xl text-white">
            Check out a protected procedure
          </Link>
        </div>
       */}
       <div className="border-r ">
         <h1>Sidebar </h1>
        </div>
       <div className="">
         <h1>Main content  </h1>
        </div>





      </main>
    </>
  );
};

export default Home;
